analytics: {}
color:
  brandColors:
    - '#C8C8E0'
    - '#309098'
    - '#80B0B8'
    - '#48B0B8'
    - '#70C0D0'
  brandStrength: 0.375
  lightness: 0.3125
  rhythmicContrast: 1
  saturation: 0.6875
cta: {}
layout_spectrum: 0.948191
name: CozartPhotos
opengraph: {}
purpose: []
typography_spectrum: 0.932566
