analytics: {}
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.503017
  lightness: 0.5625
  rhythmicContrast: 0.25
  saturation: 0.488487
cta: {}
layout_spectrum: 0.9151694481261075
name: CozartPhotos
opengraph: {}
purpose: []
typography_spectrum: 0.9817406213842332
